### ISSUE TITLE
Add HelioPy as members

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/openastronomy.github.io#105]
@dstansby - Could you do as done in #97 and add HelioPy to the list?? Thanks :)
Please, if possible add also some chatting channel (matrix?) and mailing list.

**Comment by dstansby** [comment]
Sure thing - can you assign me to this issue so I don't forget?

**Comment by dpshelio** [comment]
No I can't.... I think I need to add you to the organisation first...

**Comment by bsipocz** [comment]
@dpshelio - Yes, you can only assign people who are on a team in the org.
