### ISSUE TITLE
Make it eassier to add new organisations

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/openastronomy.github.io#117]
At the moment adding a new organisation needs to add info in the main `_config.yml` add a page under `_includes/member/` and the logo. I believe all that info could be set inside a `_members.yml` file and automatically generated the members page.

As it is now it's easier to get some minor errors like wrong logos or links.

**Comment by vedant-z** [comment]
@dpshelio May I work on this?

**Comment by dpshelio** [comment]
Sure! Go for it!

**Comment by dpshelio** [comment]
Actually... I think that #207 fixed this. I had forgotten about it.
