### ISSUE TITLE
Previous years admins are overwritten

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/openastronomy.github.io#118]
While previous mentors are kept listed, previous admins got overwritten with the current ones. Would be nice to keep track who were admin in previous years along with the mentor list:

http://openastronomy.org/gsoc/gsoc2017/

**Comment by dpshelio** [comment]
Good catch!!! - Also, this is related with my wall of fame that I started to create (not only for SoC but any other "responsibility" so it lists students and conferences committees too)
