### ISSUE TITLE
Link to openastronomy Google group

### ISSUE THREAD

**Issue by cdeil** [OpenAstronomy/openastronomy.github.io#132]
The footer at http://openastronomy.org/ contains an entry `openastronomy@googlegroups.com`

Clicking it opens the URL `mailto:openastronomy@googlegroups.com` in a new browser tab, I think it should open an email with that address filled instead?

Probably needs some change here?
https://github.com/OpenAstronomy/openastronomy.github.io/blob/18790c077c0d2e055c0656d71b6857c68e3b0f96/_includes/footer.html#L9

--

In addition, would it be possible to add a link to the openastronomy google group archive? As someone new I need to go there first and sign up, or just might want to read what's going on on that list before sending an email, no?

**Comment by Cadair** [comment]
Might just be worth changing that url to point at the Google groups page rather than an email
