### ISSUE TITLE
Add calendar

### ISSUE THREAD

**Issue by bmorris3** [OpenAstronomy/openastronomy.github.io#163]
At @bsipocz's suggestion, we should create a calendar with upcoming events/deadlines relevant to OpenAstronomy's goals.

**Comment by dpshelio** [comment]
Calendar url: https://calendar.google.com/calendar/b/1?cid=YmxoZzd0MG9zbjhscm50ZDcwOXFoZzFtaXNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

Now we need to add content and put it on the website

**Comment by bsipocz** [comment]
Also, which events could go in this calendar? The ones OpenAstronomy is involved in, or a wider range? I'm thinking about whether e.g. dotastro, astrohackweek, gaiasprint should be listed or not?

**Comment by bsipocz** [comment]
Also, what to do with smaller more focused sprints? some of them are really is focused with only ~5 people, but others are a bit more open to participations but are package focused (e.g. gammapy has regulars sprinting weeks that I believe is open to anyone, but it's really is on gammapy)?

**Comment by dpshelio** [comment]
I would add events that are open and not regular. So if gammapy is doing one that's more focus and that try to find new contributors, then it's OK. If it's a regular thing they run weekly, then that should go in their calendars. Hackdays at AAS/NAM/etc... should be there. Also particular sessions on conferences with a representation of OpenAstronomy (eg., last one at EWASS or the BoF happening at TESS).

**Comment by dpshelio** [comment]
Regarding the comment @bsipocz left on #164. Maybe an agenda view of the calendar can be added to news and events page.
