### ISSUE TITLE
Link to specific GSoC topic

### ISSUE THREAD

**Issue by cdeil** [OpenAstronomy/openastronomy.github.io#17]
Can you make it possible to link to specific GSoC projects?
http://openastronomy.github.io/gsoc2015/ideas.html

Different, but related feature request: would adding a table at the top summarising the project ideas be useful to get a quick overview?

**Comment by Cadair** [comment]
Having had a quick look online about this, it looks like the only way to do it is manually for each title `<a name="myproject"></a>`

I would quite like to use Jekyll to automatically generate the ideas page from a template, which would make it a little easier to do things like this. I do not have the skills or the time however.

**Comment by dpshelio** [comment]
It seems we've got Jekyll to do this now and with the coala project ideas page implemented.
