### ISSUE TITLE
Fix the styling on verbatim blocks in project descriptions

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/openastronomy.github.io#174]
![image](https://user-images.githubusercontent.com/1391051/50210415-f4822800-036d-11e9-979a-ba508bc5379e.png)

https://openastronomy.org/gsoc/gsoc2019/#/projects?project=incorporate_powerful_new_wcs_api_into_ndcube

**Comment by jayantsudo24** [comment]
@Cadair 
Please check my PR regarding this styling issue. :)
