### ISSUE TITLE
astropy gsoc 2020 ideas

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/openastronomy.github.io#223]
I use this issue to collect pie in the sky ideas, and we'll see how many of them can become real project ideas. cc @eteq 

- get regions and photutils to mesh better together

**Comment by bsipocz** [comment]
@larrybradley @keflavich - I have no idea any more what this project idea was about, but if you think we should pitch it for gsoc, let me know.

**Comment by larrybradley** [comment]
I'm going to be implementing this soon.  We should close this.
