### ISSUE TITLE
SunPy GSOC 2020 ideas

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/openastronomy.github.io#234]
Post your 2020 GSOC project ideas here.

**Comment by nabobalis** [comment]
glueviz solar

**Comment by wtbarnes** [comment]
[sunkit-dem](https://github.com/sunpy/sunkit-dem) -- implementing various DEM methods, ???

**Comment by wtbarnes** [comment]
[radiospectra](https://github.com/sunpy/radiospectra)

**Comment by wtbarnes** [comment]
[Space weather forecasting using machine learning](https://openastronomy.org/gsoc/gsoc2019/#/projects?project=space_weather_forecasting_using_machine_learning) -- highly dependent on whether mentors are available

**Comment by twentyse7en** [comment]
@wtbarnes Space weather forecasting using machine learning is labelled "SOCIS" , Are you planning to bring that project under GSOC this year ?

**Comment by nabobalis** [comment]
@twentyse7en It will depend on the mentors for that project (if we run it this year).

**Comment by bsipocz** [comment]
> Space weather forecasting using machine learning -- highly dependent on whether mentors are available

based on last year's experience, be careful with pitching any ML in the title, it will create a huge surge of applications with varied quality. So the mentors for that projects should be prepared to spends a significantly large amount of time before gsoc coding starts to interact with applicants.

**Comment by nabobalis** [comment]
Yeah I recall lots of applications last year and I tried to filter what I could. I assume the same would happen this year if we ran it.

**Comment by bsipocz** [comment]
Yes, but that needs to happen with the clear understanding from the mentors of any such ML themed project that someone has to do a ton of work prior the coding mentoring starts. If that someone is not those said mentors, that can work (like last year), but it needs to be a conscious  decision not something we slip into accidentally.

**Comment by nabobalis** [comment]
Thanks! If the mentors agree I will forward this message to them so they are aware of that they are signing up for.

**Comment by dpshelio** [comment]
I can change the title to: "Space weather forecast with Linear Algebra", I'm sure we then get fewer applications.

**Comment by nabobalis** [comment]
Make Fido great again.

**Comment by mbobra** [comment]
Updating PFSSPy or creating a new similar package? Contributing to AIAPy?

**Comment by mbobra** [comment]
I have time to co-mentor but I don't want to be the only mentor. If @dstansby or someone else is in, I'm happy to work on it together start putting in the time now.

**Comment by bsipocz** [comment]
> but I don't want to be the only mentor

projects with only one mentor shouldn't be run anyway :)

**Comment by dstansby** [comment]
> I have time to co-mentor but I don't want to be the only mentor. If @dstansby or someone else is in, I'm happy to work on it together start putting in the time now.

I can't think of a project off the top of my head - but if someone else can come up with a good project for extrapolations I have the time and would be happy to co-mentor.

**Comment by bsipocz** [comment]
@Cadair @nabobalis - Time to open the PR and add these ideas to the page, please. Stuff can be fine tuned later, but we need the ideas to be pitched for the application.

**Comment by nabobalis** [comment]
Sorry we forgot! I will get on that right now. As an side and a random question, how would you feel about a replacement of the website using javascript?

**Comment by bsipocz** [comment]
I don't feel anything towards the webpage. If you think it's easier to maintain, go for it. 

(I think the bigger and more important website issue is with the student/blog aggregator. That one breaks each summer for various reasons, etc. https://github.com/OpenAstronomy/Universe_OA/issues/33)

**Comment by nabobalis** [comment]
(well it might also come with an inbuilt blog)

**Comment by dpshelio** [comment]
We can close this, right? no new ideas are being expected to show up now. Please, re-open if you think it's still needed.
