### ISSUE TITLE
`--path` flag is deprecated

### ISSUE THREAD

**Issue by mikepetridisz** [OpenAstronomy/openastronomy.github.io#254]
`bundle install --path vendor/bundle` 
The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions.  We should use `bundle config set path 'vendor/bundle'`, and stop using this flag.

**Comment by dpshelio** [comment]
Thanks @mikepetridisz. Is that used anywhere or only suggested on the README? Please, open a PR if you can.

**Comment by dpshelio** [comment]
Fixed by #321
