### ISSUE TITLE
Add button/information from gsoc ideas to sub-org contacts

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/openastronomy.github.io#258]
Students find the ideas and contact the central openastronomy mailing list and then some of us have to redirect them to the messaging tool or mailing list that sub-org uses. We can skip that step if we put the info on the project description.

**Comment by godslayer201** [comment]
Hello,is this issue still open? Would like to work on this for future enhancements for future GSoCs

**Comment by ShuklaThePrashant** [comment]
Hey! i would love to close this issue if it's still open.
