### ISSUE TITLE
Potential SunPy GSOC projects 2021

### ISSUE THREAD

**Issue by dstansby** [OpenAstronomy/openastronomy.github.io#267]
Add your project ideas for SunPy as comments below:

**Comment by dstansby** [comment]
3D plotting
------------
https://github.com/sunpy/sunpy/pull/4591 has basic code for 3D plotting. The project would be to 
- Create a new package for 3D plotting of sunpy maps
- Add 3D plotting of PFSS solutions and field lines from `pfsspy`
- Other 3D plotting functionality (there are lots of extensions I can think of)

**Comment by nabobalis** [comment]
## Scarper Rewrite
[sunpy/sunpy#4888](https://github.com/sunpy/sunpy/issues/4888) is the tracking issue. The project would be to
 
* Fully scope out what we need scraper to achieve 
* Figure out how to use [parse](https://pypi.org/project/parse/) (probably with patches upstream) 
* Implement it.

**Comment by jeffreypaul15** [comment]
> ## 3D plotting
> 
> [sunpy/sunpy#4591](https://github.com/sunpy/sunpy/pull/4591) has basic code for 3D plotting. The project would be to
> 
>     * Create a new package for 3D plotting of sunpy maps
> 
>     * Add 3D plotting of PFSS solutions and field lines from `pfsspy`
> 
>     * Other 3D plotting functionality (there are lots of extensions I can think of)

I was tinkering around with ```pfsspy``` and was curious as to how the 3D plotting of PFSS solutions would be? I've understood plotting of the field lines over the AIA maps from the example but am still a tad bit confused about the PFSS solutions on a 3D plot.

**Comment by itsIapetus** [comment]
Where can I find the repository for Modern Statistical Modeling in Stingray project?

**Comment by nabobalis** [comment]
Hi @itsIapetus, I believe the repo is https://github.com/StingraySoftware/stingray

**Comment by dstansby** [comment]
Closing this since GSOC 2021 is now happening!
