### ISSUE TITLE
Add twitter handle for orgs

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/openastronomy.github.io#314]
When they have it it would be useful to list those

**Comment by JaynouOliver** [comment]
I can work on this issue. But can we be assigned before the GSoC period starts?

**Comment by bsipocz** [comment]
This one should be uncontroversial, the twitter handles could be added to orgs similar to their existing mailing list/chat service/github handles.

That being said, if you are interested in applying for GSoC, you may want to follow a different strategy. OpenAstronomy is umbrella organization, meaning that we host different member organizations and libraries, and they are the one actually advertising the coding projects. Ideally you would be familiarizing yourself with their codebases rather than the website of the umbrella org. That being said, PRs here are also very much welcome.

Project ideas are here: https://openastronomy.org/gsoc/gsoc2022/#/projects along with info of how to contact the member orgs.

**Comment by JaynouOliver** [comment]
Thank you very much!

**Comment by RajasBharambe** [comment]
Hey there, I wanted to contribute and resolve the issue !
