### ISSUE TITLE
No link to discourse on main website

### ISSUE THREAD

**Issue by dstansby** [OpenAstronomy/openastronomy.github.io#325]
The [main website](https://openastronomy.org/) doesn't seem to link to the [discourse forum](https://community.openastronomy.org/) anywhere - this should be changed!

**Comment by akshitadixit** [comment]
@dstansby if I could take this up please?

**Comment by Cadair** [comment]
Feel free to open a PR, I think this link is worthy of going in the main navigation bar.

**Comment by akshitadixit** [comment]
I'm so sorry I will take this up again and fix it.

**Comment by Cadair** [comment]
Not to worry, it's a subtle issue!

**Comment by parthsali** [comment]
Hey @Cadair, I am new to open source and would like to contribute to open source projects. Can you help me?
