### ISSUE TITLE
heliopy website is lost

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/openastronomy.github.io#329]
The heliopy project stop being developed. The website needs to update to remove it from the list of organisations.

**Comment by bsipocz** [comment]
Oh, I'm sad to hear this. Has it been merged with other efforts or rather totally abandoned?

**Comment by Cadair** [comment]
Most of it's functionality has been moved into SunPy, with https://astrospice.readthedocs.io/en/stable/ having the other major bit.

**Comment by devilkiller-ag** [comment]
Can I try to solve this issue?

**Comment by shubhamsain079** [comment]
hello sir/ma'am
I want to work on this issue , so please assign me for this
