### ISSUE TITLE
Create contact page

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/openastronomy.github.io#37]
The application asks for a webpage where to explain how to join to an IRC or mailing list.

**Comment by ngoldbaum** [comment]
for yt this information is here: http://yt-project.org/community.html

**Comment by dpshelio** [comment]
We have it in the front page... do we need it more detailed? with links to the different 'contact' page for each org, or the member page is enough?

**Comment by bsipocz** [comment]
We do have contact page for the member orgs, I think that's enough. Reopen if disagree and willing to do some code about it.
