### ISSUE TITLE
Use standard heading for difficulty/mentors/etc

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/openastronomy.github.io#4]
For Astropy we have used a standard heading format for each project which I think would be good to use for other projects:

```
*Suggested Mentor(s):* Michael Droettboom

*Difficulty:* Intermediate to Expert

*Astronomy knowledge needed:* none

*Programming skills:* Python, Unix features
```

This should be put directly under the title

**Comment by Cadair** [comment]
ping @nabobalis can you change the sunpy wiki entries to have this and to have h3 `###` headings for titles and h4 headings `####` for descriptions? You only need to do yours, and other ones that are making on to the live page.

**Comment by nabobalis** [comment]
Done? It doesn't look any different.

**Comment by astrofrog** [comment]
Ah I wonder if doing it for all of them now made them all larger again (because it realizes we skipped ``##``).

**Comment by Cadair** [comment]
@astrofrog I will look into it in a bit.

**Comment by dpshelio** [comment]
Changed format in 2017
