### ISSUE TITLE
mentors - available hours

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/openastronomy.github.io#45]
I think it would be a good idea - for next year for sure, to add the times avialability in UT for the mentors, so the candidates could now when they would be more likely to respond.

**Comment by dpshelio** [comment]
Maybe it could be added under each mentor panel with a bit of care. Need to look how `mentors.html` gets build with `app.js`

**Comment by bsipocz** [comment]
I'm going to close this now as this hasn't been acted upon. As well as I don't think it's a reasonable expectation for mentors to respond at the first chance, and therefore their UT is not really relevant for the first few async round of communication.
