### ISSUE TITLE
Decrease heading level in ideas page

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/openastronomy.github.io#6]
At the moment we include the project ideas from different pages into a single page which means that heading levels looks like:

```
# Ideas page

# Astropy

## Project 1

### Description
```

But really we want `Astropy` to be at a lower level. For now, for the Astropy project I lowered the levels of the projects and descriptions, to give:

```
# Ideas page

# Astropy

### Project 1

#### Description
```

but this is still not ideal. Any ideas?

**Comment by dpshelio** [comment]
Not needed with current format.
