### ISSUE TITLE
No mentor info

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/openastronomy.github.io#69]
Clicking on a mentor's name on the [mentor page](http://openastronomy.org/gsoc/gsoc2017/) just leads to a blank page. Seems like it should link to a page with more info or at least their GitHub profile.

**Comment by Cadair** [comment]
hmm, looks like it's a issue with the iframe hack, I don't know why it's not opening in a new tab like it's supposed to. The a tag has `target=_blank` in it.

**Comment by Cadair** [comment]
I think I fixed it in d33173f83a566c989042bc5d9823eced4345c29a
