### ISSUE TITLE
Backgrounds different on different pages

### ISSUE THREAD

**Issue by eteq** [OpenAstronomy/openastronomy.github.io#78]
I *think* this started with #64 ... I now see different backgrounds on the front page vs other pages (like "members").  Is that intended, @dpshelio and/or @Cadair ?

**Comment by Cadair** [comment]
it selects one of the two different backgrounds at random using js on page load.

**Comment by eteq** [comment]
aha!  that would explain why it seemed totally random to me.  It is! :wink:

Sorry for the noise, closing.
